server:
  port: ${PORT:9003}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/audit-service
  application:
    name: AUDIT-SERVICE

app:
  mqtt:
    broker: ${MQTT_BROKER}
    username: ${MQTT_USERNAME}
    clientId: ${spring.application.name}
    password: ${MQTT_PASSWORD}
  utils:
    auth-service-base-url: ${AUTH_SERVICE_BASE_URL}
    internal-access-token: ${INTERNAL_ACCESS_TOKEN}
    validate-path: /auth/validate
    open-api-endpoints:
