server:
  port: ${PORT:9002}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/audit
  application:
    name: AUDIT-SERVICE

app:
  mqtt:
    broker: ${MQTT_BROKER}
    client-id: ${spring.application.name}
    username: ${MQTT_USERNAME}
    password: ${MQTT_PASSWORD}
