server:
  port: ${PORT:9003}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/audit-service
  application:
    name: AUDIT-SERVICE

app:
  utils:
    auth-service-base-url: http://localhost:${server.port}
    internal-access-token: ${INTERNAL_ACCESS_TOKEN}
    validate-path: /auth/validate
    open-api-endpoints:
